### ISSUE TITLE
Old versions missing from maven.

### ISSUE THREAD

**Issue by Leolele99** [PinkGoosik/cosmetica#4]

**Comment by Leolele99** [comment]
Hey, 

could you add version 3.1 specifically (3.2 would probably also work) back to your maven?
I'd like to create a private build of the visuality mod for 1.17.1 (adding a distance options for the rain drops in water), which depends on version 3.1 of cosmetica, which is missing from your maven repo currently :)

Sorry for the inconvenience.

**Comment by PinkGoosik** [comment]
just remove it from the build script, it is not a hard dependency

**Comment by Leolele99** [comment]
I just downloaded 3.2 from your repo and added the jar manually for now!
